### ISSUE TITLE
Test fails because of missing config option

### ISSUE THREAD

**Issue by cbenz** [openfisca/openfisca-france-indirect-taxation#80]
Execution of [test_carburants_builder.py](https://github.com/openfisca/openfisca-france-indirect-taxation/blob/ec5c319b6e3bee1665b0256410aee536621a3a09/openfisca_france_indirect_taxation/tests/test_carburants_builder.py#L16) produces:

```
ERROR: Failure: NoOptionError (No option 'openfisca_indirect_taxation' in section: 'collections')
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/cbenz/Dev/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/tests/test_carburants_builder.py", line 16, in <module>
    aggregates_data_frame = get_input_data_frame(year)
  File "/home/cbenz/Dev/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/example/utils_example.py", line 29, in get_input_data_frame
    collection = "openfisca_indirect_taxation", config_files_directory = config_files_directory)
  File "/home/cbenz/Dev/openfisca/openfisca-survey-manager/openfisca_survey_manager/survey_collections.py", line 120, in load
    json_file_path = config.get("collections", collection)
  File "/usr/lib/python2.7/ConfigParser.py", line 618, in get
    raise NoOptionError(option, section)
NoOptionError: No option 'openfisca_indirect_taxation' in section: 'collections'
```

**Comment by benjello** [comment]
@thomasdouenne is fixing this issue

**Comment by benjello** [comment]
fixed
