### ISSUE TITLE
Non working test_carburants_builder.py

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-indirect-taxation#81]
```
======================================================================
ERROR: Failure: KeyError ("['categorie_fiscale_14'] not in index")
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/tests/test_carburants_builder.py", line 41, in <module>
    df2 = aggregates_data_frame[['poste_coicop_722'] + ['categorie_fiscale_14']]
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 1963, in __getitem__
    return self._getitem_array(key)
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 2007, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "/usr/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1150, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['categorie_fiscale_14'] not in index"
```

**Comment by cbenz** [comment]
Is it related to new variables syntax merge https://github.com/openfisca/openfisca-core/pull/364 ?

**Comment by benjello** [comment]
This bugs are data related (test-ci are working). They are for @thomasdouenne ;-)

**Comment by benjello** [comment]
Fixed

**Comment by benjello** [comment]
Still a warning to deal with
