### ISSUE TITLE
Non working tests_aids_categ.py

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-indirect-taxation#82]
```
======================================================================
ERROR: Failure: KeyError ("['_1000' '_2000' '_3000' '_4000' '_5000' '_6000' '_7000' '_8000' '_9000'\n '_10000' '_11000' '_12000'] not in index")
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/tests/tests_aids_categ.py", line 10, in <module>
    from openfisca_france_indirect_taxation.almost_ideal_demand_system.aids_dataframe_builder_categ import \
  File "/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/almost_ideal_demand_system/aids_dataframe_builder_categ.py", line 152, in <module>
    ['_7000'] + ['_8000'] + ['_9000'] + ['_10000'] + ['_11000'] + ['_12000'] + ['temps'] + ['date']]
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 1963, in __getitem__
    return self._getitem_array(key)
  File "/usr/lib/python2.7/dist-packages/pandas/core/frame.py", line 2007, in _getitem_array
    indexer = self.ix._convert_to_indexer(key, axis=1)
  File "/usr/lib/python2.7/dist-packages/pandas/core/indexing.py", line 1150, in _convert_to_indexer
    raise KeyError('%s not in index' % objarr[mask])
KeyError: "['_1000' '_2000' '_3000' '_4000' '_5000' '_6000' '_7000' '_8000' '_9000'\n '_10000' '_11000' '_12000'] not in index"
```

**Comment by benjello** [comment]
fixed

**Comment by benjello** [comment]
Still buggy and present in the tests as you can see
````shell
benjello@WKS-IPP-6:~/openfisca/openfisca-france-indirect-taxation(master *%=)$ nosetests openfisca_france_indirect_taxation/tests/tests_aids_categ.py 
E
======================================================================
ERROR: Failure: ImportError (No module named aids_dataframe_builder_categ)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/tests/tests_aids_categ.py", line 10, in <module>
    from openfisca_france_indirect_taxation.almost_ideal_demand_system.aids_dataframe_builder_categ import \
ImportError: No module named aids_dataframe_builder_categ

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
````
What should we do with it @thomasdouenne ?

**Comment by thomasdouenne** [comment]
We should not use this test anymore, it was made to test if there was no mistake in aids_dataframe_builder_categ. Since it does not exist anymore, the test is irrelevant. We can however use this test to create a new one for aids_dataframe_builder_energy.
