### ISSUE TITLE
Non working tests

### ISSUE THREAD

**Issue by benjello** [openfisca/openfisca-france-indirect-taxation#84]
```
nosetests openfisca_france_indirect_taxation/tests/test_age.py 
E
======================================================================
ERROR: Failure: IOError (could not find class definition)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/nose/loader.py", line 420, in loadTestsFromName
    addr.filename, addr.module)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 47, in importFromPath
    return self.importFromDir(dir_path, fqname)
  File "/usr/lib/python2.7/dist-packages/nose/importer.py", line 94, in importFromDir
    mod = load_module(part_fqname, fh, filename, desc)
  File "/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/tests/test_age.py", line 30, in <module>
    from . import base
  File "/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/tests/base.py", line 38, in <module>
    TaxBenefitSystem = init_country()
  File "/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/__init__.py", line 53, in init_country
    from .model import model  # noqa analysis:ignore
  File "/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/model/model.py", line 30, in <module>
    from .consommation import (  # noqa analysis:ignore
  File "/home/benjello/openfisca/openfisca-france-indirect-taxation/openfisca_france_indirect_taxation/model/consommation/consommation_menages.py", line 37, in <module>
    label = u"Poste coicop {} de la nomenclature aggrégée à 12 niveaux".format(coicop12_index),
  File "/home/benjello/openfisca/openfisca-core/openfisca_core/formulas.py", line 968, in __new__
    source_lines, line_number = inspect.getsourcelines(self)
  File "/usr/lib/python2.7/inspect.py", line 690, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python2.7/inspect.py", line 564, in findsource
    raise IOError('could not find class definition')
IOError: could not find class definition

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by benjello** [comment]
@cbenz : I need you on this ;-)

**Comment by cbenz** [comment]
Fixed.

For the record, involved commits are bc0f4f503e66bc8babbbc90c6e3378a8be0b5cc6 (my fault) and https://github.com/openfisca/openfisca-core/commit/d62ff6b0eb3e81f4ceebdbee2d64e0c90848c20a which lets the Core be more tolerant to dynamically-generated `Variable` classes like [here](https://github.com/openfisca/openfisca-france-indirect-taxation/blob/ccc5579c9c23f871d833ddd7cffbe5917c921172/openfisca_france_indirect_taxation/model/consommation/consommation_menages.py#L32-L38).
